### ISSUE TITLE
Invalid JSON primitive, task not working

### ISSUE THREAD

**Issue by roofiq** [sam-cogan/arm-ttk-extension#23]
Hey, I'm having same issue.
Here is error I'm getting:
```
Starting: RunARMTTKTests
==============================================================================
Task         : Run Azure RM TTK Tests
Description  : Run Azure Resource Manager Template Test Kit Tests against ARM Templates
Version      : 1.0.7
Author       : Sam Cogan
Help         : [More Information](https://github.com/sam-cogan/arm-ttk-extension/blob/master/README.md)
==============================================================================
##[error]Invalid JSON primitive: .
##[error]Failures found in test results
Finishing: RunARMTTKTests
```

I have a main template called. build.yml and a side one called build-step.yml. In this site template I have added a step with your task.
```
  - task: RunARMTTKTests@1
    inputs:
      templatelocation: '$(System.DefaultWorkingDirectory)\ARM\KeyVault.json'
      resultLocation: '$(System.DefaultWorkingDirectory)\results'
```

In ARM templates folder I have all the generic templates for different resource and other folder called ParametersExamples.
Even if in template location I'm passing only folder, it fails with same error.

Thanks for help

_Originally posted by @roofiq in https://github.com/sam-cogan/arm-ttk-extension/issues/6#issuecomment-679979845_

**Comment by sam-cogan** [comment]
Any chance you could provide a copy of the template(s) that is causing the error?

**Comment by roofiq** [comment]
Yes, I can share. I have customized it, but the error still occurs so it's good example.

The task:
```
      - task: RunARMTTKTests@1
        inputs:
          templatelocation: '$(System.DefaultWorkingDirectory)\ARM\Redis.json'
          resultLocation: '$(System.DefaultWorkingDirectory)\tt.xml'
```

Redis.json:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "redisName": {
            "type": "string",
            "metadata": {
                "docs": "https://docs.microsoft.com/en-us/azure/templates/microsoft.cache/2019-07-01/redis"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]"
        },
        "zones": {
            "type": "array",
            "defaultValue": [],
            "metadata": {
                "description": "A list of availability zones denoting where the resource needs to come from"
            }
        },
        "redisConfiguration": {
            "type": "object",
            "defaultValue": {}
        },
        "enableNonSslPort": {
            "type": "bool",
            "defaultValue": false
        },
        "replicasPerMaster": {
            "type": "int",
            "defaultValue": 0
        },
        "tenantSettings": {
            "type": "object",
            "defaultValue": {}
        },
        "shardCount": {
            "type": "int",
            "defaultValue": 0
        },
        "minimumTlsVersion": {
            "type": "string"
        },
        "skuName": {
            "type": "string",
            "allowedValues": [
                "Basic",
                "Standard",
                "Premium"
            ]
        },
        "skuFamily": {
            "type": "string",
            "allowedValues": [
                "C",
                "P"
            ]
        },
        "skuCapacity": {
            "type": "int",
            "minValue": 0,
            "maxValue": 6
        },
        "subnetId": {
            "type": "string",
            "defaultValue": "",
            "metadata": {
                "description": "The full resource ID of a subnet in a virtual network to deploy the Redis cache in. Example format: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/Microsoft.{NetworkClassicNetwork}/VirtualNetworks/vnet1/subnets/subnet1"
            }
        },
        "staticIP": {
            "type": "string",
            "defaultValue": "",
            "metadata": {
                "description": "Static IP address. Required when deploying a Redis cache inside an existing Azure Virtual Network"
            }
        },
        "tags": {
            "type": "object",
            "defaultValue": {
            }
        },
        "shouldDeploy": {
            "type": "bool",
            "defaultValue": true
        }
    },
    "functions": [],
    "variables": {},
    "resources": [
        {
            "condition": "[parameters('shouldDeploy')]",
            "type": "Microsoft.Cache/redis",
            "name": "[parameters('redisName')]",
            "apiVersion": "2019-07-01",
            "location": "[parameters('location')]",
            "zones": "[if(not(empty(parameters('zones'))), parameters('zones'), json('null'))]",
            "tags": "[parameters('tags')]",
            "properties": {
                "redisConfiguration": "[parameters('redisConfiguration')]",
                "enableNonSslPort": "[parameters('enableNonSslPort')]",
                "minimumTlsVersion": "[parameters('minimumTlsVersion')]",
                "replicasPerMaster": "[if(equals(parameters('skuName'), 'Premium'), parameters('replicasPerMaster'), json('null'))]",
                "shardCount": "[if(equals(parameters('skuName'), 'Premium'), parameters('shardCount'), json('null'))]",
                "tenantSettings": "[parameters('tenantSettings')]",
                "sku": {
                    "name": "[parameters('skuName')]",
                    "family": "[parameters('skuFamily')]",
                    "capacity": "[parameters('skuCapacity')]"
                },
                "staticIP": "[if(not(empty(parameters('staticIP'))), parameters('staticIP'), json('null'))]",
                "subnetId": "[if(not(empty(parameters('subnetId'))), parameters('subnetId'), json('null'))]"
            }
        }
    ],
    "outputs": {
    }
}
```

Thank you for help :)

**Comment by sam-cogan** [comment]
Excellent, thanks for that. Let me look into that and I'll get back to you.

**Comment by roofiq** [comment]
Hey @sam-cogan, do you have any update on this? :)

**Comment by sam-cogan** [comment]
No, not yet. It will likely need to wait till the weekend.

**Comment by sam-cogan** [comment]
@roofiq I've been looking at this issue, but unfortunately when testing the file you supplied it seems to work fine, all tests pass. When you tested, is this the only ARM template in the folder? If your able to, would you be able to send me the file directly, just in case Github is doing something to them? You can email them to mail at samcogan.com

**Comment by roofiq** [comment]
@sam-cogan, in ARM folder, there are mutliple files. Also in this folder, there is folder ParamExamples, which as well has mutliple json files.
I will try to test it again, checking different scenarios.

**Comment by roofiq** [comment]
Hey @sam-cogan, so I have extremely simplified the issue here. I have minimized number of files.

Files in the repository:
- `build.yml`
- `Redis.json`

`Redis.json` is as I have pasted few comments above. I have even recopied it from the comment in case github messed up formatting.
`build.yml` is as like below:
```
trigger: none

pool:
  vmImage: windows-latest

jobs:
- job: TestARMTTK
  steps:
  - task: RunARMTTKTests@1
    inputs:
      templatelocation: '$(System.DefaultWorkingDirectory)'
      resultLocation: '$(System.DefaultWorkingDirectory)'
```
In this scenario, I'm not getting this json primitive error, but just that it **have found failures in test results**.
![image](https://user-images.githubusercontent.com/44588684/91977121-6eb13680-ed22-11ea-9a34-32567cee6378.png)

This error is the same, even if I'm passing direct file to `templateLocation`, in this example: `'$(System.DefaultWorkingDirectory)\Redis.json'`.
But when I have entered some non existing file, it throws with error:
`##[error]Template Location is not an existing folder, file or wildcard`

It seems like the issue is somewhere in processing the file.
Hope it will help you to find issue! Maybe you can share with template file, that is working for you and I can test it out?

Cheers,
Rafał

**Comment by sam-cogan** [comment]
@roofiq  I've taken both the files you mentioned and added them to the repo here - https://github.com/sam-cogan/ttkdebug
When I run this, they all pass without issue. Can have a look at the build.yaml in that repo and add the test results step to your pipeline? This should show the results and let us see what tests it thinks are failing.

**Comment by bjh1977** [comment]
I'm also hitting this issue:

YAML:
```      
     - task: RunARMTTKTests@1
        inputs:
          templatelocation: '$(System.DefaultWorkingDirectory)\provisioning\alerts\AlertGroup\arm_template.json'
          resultLocation: '$(System.DefaultWorkingDirectory)\ARM-TTK.XML'
      
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)\*-armttk.xml'
        condition: always()
```

RESULT:
```##[debug]Loading module from path 'D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\invoke-ttk.psm1'.
##[debug]Exporting function 'Test-FolderContents'.
##[debug]Exporting function 'Invoke-TTK'.
##[debug]Importing function 'Invoke-TTK'.
##[debug]Importing function 'Test-FolderContents'.
##[debug]INPUT_TEMPLATELOCATION: 'D:\a\1\s\provisioning\alerts\AlertGroup\arm_template.json'
##[debug]INPUT_RESULTLOCATION: 'D:\a\1\s\ARM-TTK.XML'
##[debug]INPUT_INCLUDETESTS (empty)
##[debug]INPUT_SKIPTESTS (empty)
##[debug]Error record:
##[debug]Import-Json : Invalid JSON primitive: .
##[debug]At D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\arm-ttk\Expand-AzTemplate.ps1:216 char:50
##[debug]+ ...                 $fileObject.Object = Import-Json $fileObject.FullPath
##[debug]+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (D:\a\1\s\provis...parameters.json:String) [Import-Json], ArgumentExce    ption
##[debug]    + FullyQualifiedErrorId : Import.Json.Failed,Import-Json
##[debug] 
##[debug]Script stack trace:
##[debug]at Import-Json<Process>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\arm-ttk\Import-Json.ps1: line 29
##[debug]at <ScriptBlock>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\arm-ttk\Expand-AzTemplate.ps1: line 216
##[debug]at Expand-AzTemplate<Process>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\arm-ttk\Expand-AzTemplate.ps1: line 194
##[debug]at Test-AzTemplate<End>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\arm-ttk\Test-AzTemplate.ps1: line 426
##[debug]at Test-FolderContents, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\invoke-ttk.psm1: line 12
##[debug]at Invoke-TTK, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\invoke-ttk.psm1: line 75
##[debug]at <ScriptBlock>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.7\powershell.ps1: line 28
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ArgumentException: Invalid JSON primitive: .
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeList(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
##[debug]   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
##[debug]   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Invalid JSON primitive: .
##[debug]Processed: ##vso[task.logissue type=error]Invalid JSON primitive: .
Finishing: RunARMTTKTests
```

When I run `Test-AzTemplate` locally against the same file, the tests run successfully.

**Comment by sam-cogan** [comment]
@bjh1977 any chance you can supply the template your testing?

**Comment by bjh1977** [comment]
@sam-cogan  Sure: https://gist.github.com/bjh1977/96d33432dacf875cc979bcefcd2c016f

**Comment by roofiq** [comment]
Hey @sam-cogan, sorry for that pull request. I misunderstood in the first place 👍 
So I have copied this yaml file and run this pipeline. I have enabled system diagnostic for this one. So it is quite interesting, because this step failed again but the results have been published correctly. Below logs.

I have uploaded them as files, because they are pretty long.

RunARMTTKTests logs:
[runarmttktests-logs.txt](https://github.com/sam-cogan/arm-ttk-extension/files/5168267/runarmttktests-logs.txt)

PublishTestResults logs:
[publishtestresults-logs.txt](https://github.com/sam-cogan/arm-ttk-extension/files/5168260/publishtestresults-logs.txt)

And the output result looks as it has been processed. Below screenshot.
![image](https://user-images.githubusercontent.com/44588684/92111079-0c246d00-edec-11ea-8c12-9dd3cc41a345.png)

**Comment by sam-cogan** [comment]
@roofiq what you are seeing now is expected. It looks like you are failing one of the tests, the extension is designed to fail the task if you fail a test, so it is behaving as normal. The publish test results step is set to run regardless of whether the test task failed or passed, so that it shows the results. You need to look at the test results and see which test is failing, and determine if that is valid or not.

**Comment by sam-cogan** [comment]
@bjh1977 I haven't tested yet, however you issue may be this line:
        `  resultLocation: '$(System.DefaultWorkingDirectory)\ARM-TTK.XML'`
The results location needs to be a folder, not a file name. The task creates a file for each arm template it tests inside that folder. Can you try setting it just to a folder rather than a file name please?

**Comment by bjh1977** [comment]
@sam-cogan I made the change you suggested.  The result was no different.

Also, I just accepted the default in Azure Devops, so maybe that needs changing:

![image](https://user-images.githubusercontent.com/14811651/92121321-0d589880-edf2-11ea-93b3-7d6e186498b7.png)

**Comment by roofiq** [comment]
Hello, so I'm still getting this Invalid JSON primitive, but the test is being done so I guess we could close this issue :)
I have applied continueOnError feature so it is fulfilling my requirements.

Thanks for help.
